// <auto-generated />
namespace OnlineVotingAndroid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcandidateandvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcandidateandvote));
        
        string IMigrationMetadata.Id
        {
            get { return "202203020754450_add candidate and vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
