// <auto-generated />
namespace OnlineVotingAndroid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration5722 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration5722));
        
        string IMigrationMetadata.Id
        {
            get { return "202205071031070_migration5722"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
